### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [mobilepermissions/mobilepermissions_bc#1]
Hi:
I am looking at possibly reusing some of your code (gradle and manifest) in https://github.com/nexB/scancode-toolkit
What would be the license of this fine code?
Thank you!

**Comment by bbchristians** [comment]
Hi @pombredanne,

Feel free to re-use any code from this repository, just make sure to cite our research: https://dl.acm.org/citation.cfm?id=3341979

Let me know if you have any questions,
Ben
